postgres:
  image: postgres:9.5
  ports:
    - "5431:5432"
  environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
tomcat:
  build: tomcat-opencms/
  ports:
    - "8888:8080"
  links:
    - postgres
